server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://jdbc:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:cn/**/mapper/*.xml
